image:
  - Visual Studio 2017

configuration:
  - Debug

build:
  project: C:\Projects\rapidstring\build\rapidstring.sln

install:
  - git submodule update --init --recursive

before_build:
  - mkdir build
  - cd build
  - cmake .. -G "Visual Studio 15 2017 Win64" -DBUILD_TESTING=1 -Werror=dev

test_script:
  - cd C:\Projects\rapidstring\build\test\%CONFIGURATION%
  - .\rapidstring_test.exe
